CREATE TABLE ARVORE(
ID SERIAL PRIMARY KEY,
NOME_C VARCHAR(300) NOT NULL,
NAT_EXO CHAR(8) NOT NULL,
HORARIO TIMESTAMP NOT NULL,
LOCALIZACAO VARCHAR(300) NOT NULL,
VEGETACAO VARCHAR(300) NOT NULL,
ESPECIE VARCHAR(300) NOT NULL,
DIAMETRO_PEITO VARCHAR(50) NOT NULL,
ESTADO_FITOSSANITARIO VARCHAR(300) NOT NULL,
ESTADO_TRONCO VARCHAR(300) NOT NULL,
ESTADO_COPA VARCHAR(300) NOT NULL,
TAMANHO_CALCADA VARCHAR(300) NOT NULL,
ESPACO_ARVORE VARCHAR(300) NOT NULL,
RAIZES VARCHAR(300) NOT NULL,
ACESSIBILIDADE VARCHAR(300) NOT NULL,
CURIOSIDADE VARCHAR(350) NOT NULL
);

CREATE TABLE NOMES_POPULARES_ARVORE(
ID_NOME_ARVORE SERIAL PRIMARY KEY,
FK_ARVORE INT NOT NULL,
FK_NP INT NOT NULL
);

CREATE TABLE NOMES_POPULARES(
ID_NOME SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORIA(
	ID_CATEGORIA SERIAL PRIMARY KEY,
	NOME_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE LINKS(
	ID_LINKS SERIAL PRIMARY KEY,
	LINK VARCHAR(150) NOT NULL
);

CREATE TABLE CATEGORIA_LINKS(
	ID_CA SERIAL PRIMARY KEY,
	FK_CATEGORIA INT NOT NULL,
	FK_ARVORE INT NOT NULL,
	FK_LINKS INT NOT NULL
);

ALTER TABLE CATEGORIA_LINKS
ADD CONSTRAINT FK_ID_CATEGORIA
FOREIGN KEY (FK_CATEGORIA)
REFERENCES CATEGORIA(ID_CATEGORIA);

ALTER TABLE CATEGORIA_LINKS
ADD CONSTRAINT FK_ID_LINKS
FOREIGN KEY (FK_LINKS)
REFERENCES LINKS(ID_LINKS);
 
ALTER TABLE CATEGORIA_LINKS
ADD CONSTRAINT FK_ID_ARVORE
FOREIGN KEY (FK_ARVORE)
REFERENCES ARVORE(ID);
 
ALTER TABLE NOMES_POPULARES_ARVORE
ADD CONSTRAINT FK_ID_ARVORE
FOREIGN KEY (FK_ARVORE)
REFERENCES ARVORE(ID);
 
ALTER TABLE NOMES_POPULARES_ARVORE
ADD CONSTRAINT FK_ID_NP
FOREIGN KEY (FK_NP)
REFERENCES NOMES_POPULARES(ID_NOME);
 
-- Adicionando um índice para otimizar as buscas por FK_ARVORE
CREATE INDEX idx_fk_arvore_categoria_links ON CATEGORIA_LINKS (FK_ARVORE);

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('imagem_fruto');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('imagem_folha');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('imagem_casca');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('imagem_habito');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('imagem_flor');
 
CREATE UNIQUE INDEX idx_nomes_populares_lower_nome ON nomes_populares (LOWER(nome));


-- Select dos links por categoria 

SELECT L.LINK FROM LINKS L JOIN CATEGORIA_LINKS CL ON CL.FK_LINKS = L.ID_LINKS
JOIN CATEGORIA C ON C.ID_CATEGORIA = CL.FK_CATEGORIA
WHERE C.NOME_CATEGORIA = 'COPA';


-- Select das informações da arvore por nome cientifico
-- Se quiser alterar para nomes populares é só substituir o A.NOME_C do where por NP.NOME
 
SELECT NP.NOME AS NOME_POPULAR, A.NOME_C AS NOME_CIENTIFICO, A.HORARIO, A.LOCALIZACAO, A.VEGETACAO, A.ESPECIE, A.DIAMETRO_PEITO,
A.ESTADO_FITOSSANITARIO, A.ESTADO_TRONCO, A.ESTADO_COPA, A.TAMANHO_CALCADA, A.ESPACO_ARVORE, A.RAIZES, A.ACESSIBILIDADE,
A.CURIOSIDADE 
FROM ARVORE A JOIN NOMES_POPULARES_ARVORE NPA ON A.ID = NPA.FK_ARVORE
JOIN NOMES_POPULARES NP ON NP.ID_NOME = NPA.FK_NP WHERE A.NOME_C = 'NOME';
 
-- Updates

UPDATE NOMES_POPULARES SET NOME = 'Carinha' WHERE ID_NOME = 1;
 
UPDATE ARVORE SET
	NOME_C = 'NOME', 
	NAT_EXO = 'EXOTICA',
	HORARIO = '2025-08-21 18:08:09',
	LOCALIZACAO = 'LÁ', 
	VEGETACAO = 'SIM',
	ESPECIE = 'BOA',
	DIAMETRO_PEITO = 'SIM',
	ESTADO_FITOSSANITARIO = 'NAO TEM',
	ESTADO_TRONCO = 'RUIM',
	ESTADO_COPA = 'BOM',
	TAMANHO_CALCADA = 'SUFICIENTE',
	ESPACO_ARVORE = 'TEM',
	RAIZES = 'NAO TEM',
	ACESSIBILIDADE = 'OK',
	CURIOSIDADE = 'BACANA'
WHERE ID = 1;

ALTER TABLE arvore
ADD COLUMN latitude DECIMAL(10, 8) NULL,
ADD COLUMN longitude DECIMAL(11, 8) NULL;